describe("cron", function()
    local cron = require("motebase.cron")

    before_each(function()
        cron.clear()
    end)

    describe("add", function()
        it("adds a cron job with standard expression", function()
            local ok = cron.add("test", "0 * * * *", function() end)
            assert.is_true(ok)

            local job = cron.get("test")
            assert.is_not_nil(job)
            assert.are.equal("test", job.id)
            assert.are.equal("0 * * * *", job.expression)
        end)

        it("adds a cron job with macro", function()
            local ok = cron.add("hourly", "@hourly", function() end)
            assert.is_true(ok)
        end)

        it("rejects invalid expression", function()
            local ok, err = cron.add("bad", "invalid", function() end)
            assert.is_nil(ok)
            assert.is_string(err)
        end)

        it("rejects empty id", function()
            local ok, err = cron.add("", "0 * * * *", function() end)
            assert.is_nil(ok)
            assert.is_string(err)
        end)

        it("rejects non-function handler", function()
            local ok, err = cron.add("test", "0 * * * *", "not a function")
            assert.is_nil(ok)
            assert.is_string(err)
        end)
    end)

    describe("remove", function()
        it("removes an existing job", function()
            cron.add("removable", "0 * * * *", function() end)
            assert.is_not_nil(cron.get("removable"))

            cron.remove("removable")
            assert.is_nil(cron.get("removable"))
        end)
    end)

    describe("list", function()
        it("lists all jobs", function()
            cron.add("job_a", "@hourly", function() end)
            cron.add("job_b", "@daily", function() end)

            local list = cron.list()
            assert.are.equal(2, #list)
            assert.are.equal("job_a", list[1].id)
            assert.are.equal("job_b", list[2].id)
        end)
    end)

    describe("expression parsing", function()
        it("parses single values", function()
            local ok = cron.add("t", "30 14 * * *", function() end)
            assert.is_true(ok)
        end)

        it("parses ranges", function()
            local ok = cron.add("t", "0 9-17 * * *", function() end)
            assert.is_true(ok)
        end)

        it("parses step values", function()
            local ok = cron.add("t", "*/15 * * * *", function() end)
            assert.is_true(ok)
        end)

        it("parses comma-separated values", function()
            local ok = cron.add("t", "0 0 1,15 * *", function() end)
            assert.is_true(ok)
        end)

        it("parses all macros", function()
            assert.is_true(cron.add("yearly", "@yearly", function() end))
            cron.remove("yearly")
            assert.is_true(cron.add("monthly", "@monthly", function() end))
            cron.remove("monthly")
            assert.is_true(cron.add("weekly", "@weekly", function() end))
            cron.remove("weekly")
            assert.is_true(cron.add("daily", "@daily", function() end))
            cron.remove("daily")
            assert.is_true(cron.add("hourly", "@hourly", function() end))
        end)
    end)

    describe("start/stop", function()
        it("tracks running state", function()
            assert.is_false(cron.is_running())

            cron.start()
            assert.is_true(cron.is_running())

            cron.stop()
            assert.is_false(cron.is_running())
        end)
    end)
end)
